/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'id' : ApplicationId,
  'appliedAt' : Timestamp,
  'interviewId' : [] | [InterviewId],
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
  'skills' : string,
  'qualification' : string,
}
export type ApplicationId = bigint;
export interface ApplicationInput {
  'interviewId' : [] | [InterviewId],
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
  'skills' : string,
  'qualification' : string,
}
export interface Interview {
  'id' : InterviewId,
  'jobRole' : string,
  'date' : string,
  'createdAt' : Timestamp,
  'time' : string,
  'description' : string,
  'isActive' : boolean,
  'company' : string,
  'location' : string,
}
export type InterviewId = bigint;
export interface NewShiftJob {
  'jobRole' : string,
  'description' : string,
  'company' : string,
  'shiftStart' : string,
  'shiftEnd' : string,
  'shiftType' : string,
  'location' : string,
}
export interface ShiftJob {
  'id' : ShiftJobId,
  'jobRole' : string,
  'createdAt' : bigint,
  'description' : string,
  'isActive' : boolean,
  'company' : string,
  'shiftStart' : string,
  'shiftEnd' : string,
  'shiftType' : string,
  'location' : string,
}
export type ShiftJobId = bigint;
export type Timestamp = bigint;
export interface _SERVICE {
  'addShiftJob' : ActorMethod<[NewShiftJob], ShiftJob>,
  'getActiveInterviews' : ActorMethod<[], Array<Interview>>,
  'getAllApplications' : ActorMethod<[], Array<Application>>,
  'getInterview' : ActorMethod<[InterviewId], [] | [Interview]>,
  'getShiftJobs' : ActorMethod<[], Array<ShiftJob>>,
  'submitApplication' : ActorMethod<
    [ApplicationInput],
    { 'ok' : string } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];