/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const NewShiftJob = IDL.Record({
  'jobRole' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'shiftStart' : IDL.Text,
  'shiftEnd' : IDL.Text,
  'shiftType' : IDL.Text,
  'location' : IDL.Text,
});
export const ShiftJobId = IDL.Nat;
export const ShiftJob = IDL.Record({
  'id' : ShiftJobId,
  'jobRole' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'company' : IDL.Text,
  'shiftStart' : IDL.Text,
  'shiftEnd' : IDL.Text,
  'shiftType' : IDL.Text,
  'location' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const InterviewId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Interview = IDL.Record({
  'id' : InterviewId,
  'jobRole' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'company' : IDL.Text,
  'location' : IDL.Text,
});
export const ApplicationId = IDL.Nat;
export const Application = IDL.Record({
  'id' : ApplicationId,
  'appliedAt' : Timestamp,
  'interviewId' : IDL.Opt(InterviewId),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'skills' : IDL.Text,
  'qualification' : IDL.Text,
});
export const UserId = IDL.Principal;
export const UserProfile = IDL.Record({
  'id' : UserId,
  'createdAt' : Timestamp,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
});
export const UserProfileInput = IDL.Record({
  'fullName' : IDL.Text,
  'email' : IDL.Text,
});
export const ApplicationInput = IDL.Record({
  'interviewId' : IDL.Opt(InterviewId),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'skills' : IDL.Text,
  'qualification' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addShiftJob' : IDL.Func([NewShiftJob], [ShiftJob], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getActiveInterviews' : IDL.Func([], [IDL.Vec(Interview)], ['query']),
  'getAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInterview' : IDL.Func([InterviewId], [IDL.Opt(Interview)], ['query']),
  'getShiftJobs' : IDL.Func([], [IDL.Vec(ShiftJob)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func(
      [UserProfileInput],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
      [],
    ),
  'submitApplication' : IDL.Func(
      [ApplicationInput],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const NewShiftJob = IDL.Record({
    'jobRole' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'shiftStart' : IDL.Text,
    'shiftEnd' : IDL.Text,
    'shiftType' : IDL.Text,
    'location' : IDL.Text,
  });
  const ShiftJobId = IDL.Nat;
  const ShiftJob = IDL.Record({
    'id' : ShiftJobId,
    'jobRole' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'company' : IDL.Text,
    'shiftStart' : IDL.Text,
    'shiftEnd' : IDL.Text,
    'shiftType' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const InterviewId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Interview = IDL.Record({
    'id' : InterviewId,
    'jobRole' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'company' : IDL.Text,
    'location' : IDL.Text,
  });
  const ApplicationId = IDL.Nat;
  const Application = IDL.Record({
    'id' : ApplicationId,
    'appliedAt' : Timestamp,
    'interviewId' : IDL.Opt(InterviewId),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'skills' : IDL.Text,
    'qualification' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const UserProfile = IDL.Record({
    'id' : UserId,
    'createdAt' : Timestamp,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
  });
  const UserProfileInput = IDL.Record({
    'fullName' : IDL.Text,
    'email' : IDL.Text,
  });
  const ApplicationInput = IDL.Record({
    'interviewId' : IDL.Opt(InterviewId),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'skills' : IDL.Text,
    'qualification' : IDL.Text,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addShiftJob' : IDL.Func([NewShiftJob], [ShiftJob], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getActiveInterviews' : IDL.Func([], [IDL.Vec(Interview)], ['query']),
    'getAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInterview' : IDL.Func([InterviewId], [IDL.Opt(Interview)], ['query']),
    'getShiftJobs' : IDL.Func([], [IDL.Vec(ShiftJob)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func(
        [UserProfileInput],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text })],
        [],
      ),
    'submitApplication' : IDL.Func(
        [ApplicationInput],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };