/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'id' : ApplicationId,
  'appliedAt' : Timestamp,
  'interviewId' : [] | [InterviewId],
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
  'skills' : string,
  'qualification' : string,
}
export type ApplicationId = bigint;
export interface ApplicationInput {
  'interviewId' : [] | [InterviewId],
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
  'skills' : string,
  'qualification' : string,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Interview {
  'id' : InterviewId,
  'jobRole' : string,
  'date' : string,
  'createdAt' : Timestamp,
  'time' : string,
  'description' : string,
  'isActive' : boolean,
  'company' : string,
  'location' : string,
}
export type InterviewId = bigint;
export interface NewShiftJob {
  'jobRole' : string,
  'description' : string,
  'company' : string,
  'shiftStart' : string,
  'shiftEnd' : string,
  'shiftType' : string,
  'location' : string,
}
export type Result = { 'ok' : null } |
  { 'err' : Error };
export interface ShiftJob {
  'id' : ShiftJobId,
  'jobRole' : string,
  'createdAt' : bigint,
  'description' : string,
  'isActive' : boolean,
  'company' : string,
  'shiftStart' : string,
  'shiftEnd' : string,
  'shiftType' : string,
  'location' : string,
}
export type ShiftJobId = bigint;
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'createdAt' : Timestamp,
  'fullName' : string,
  'email' : string,
}
export interface UserProfileInput { 'fullName' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addShiftJob' : ActorMethod<[NewShiftJob], ShiftJob>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getActiveInterviews' : ActorMethod<[], Array<Interview>>,
  'getAllApplications' : ActorMethod<[], Array<Application>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInterview' : ActorMethod<[InterviewId], [] | [Interview]>,
  'getShiftJobs' : ActorMethod<[], Array<ShiftJob>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<
    [UserProfileInput],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'submitApplication' : ActorMethod<
    [ApplicationInput],
    { 'ok' : string } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];