/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NewShiftJob = IDL.Record({
  'jobRole' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'shiftStart' : IDL.Text,
  'shiftEnd' : IDL.Text,
  'shiftType' : IDL.Text,
  'location' : IDL.Text,
});
export const ShiftJobId = IDL.Nat;
export const ShiftJob = IDL.Record({
  'id' : ShiftJobId,
  'jobRole' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'company' : IDL.Text,
  'shiftStart' : IDL.Text,
  'shiftEnd' : IDL.Text,
  'shiftType' : IDL.Text,
  'location' : IDL.Text,
});
export const InterviewId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Interview = IDL.Record({
  'id' : InterviewId,
  'jobRole' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'company' : IDL.Text,
  'location' : IDL.Text,
});
export const ApplicationId = IDL.Nat;
export const Application = IDL.Record({
  'id' : ApplicationId,
  'appliedAt' : Timestamp,
  'interviewId' : IDL.Opt(InterviewId),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'skills' : IDL.Text,
  'qualification' : IDL.Text,
});
export const ApplicationInput = IDL.Record({
  'interviewId' : IDL.Opt(InterviewId),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'skills' : IDL.Text,
  'qualification' : IDL.Text,
});

export const idlService = IDL.Service({
  'addShiftJob' : IDL.Func([NewShiftJob], [ShiftJob], []),
  'getActiveInterviews' : IDL.Func([], [IDL.Vec(Interview)], ['query']),
  'getAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getInterview' : IDL.Func([InterviewId], [IDL.Opt(Interview)], ['query']),
  'getShiftJobs' : IDL.Func([], [IDL.Vec(ShiftJob)], ['query']),
  'submitApplication' : IDL.Func(
      [ApplicationInput],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NewShiftJob = IDL.Record({
    'jobRole' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'shiftStart' : IDL.Text,
    'shiftEnd' : IDL.Text,
    'shiftType' : IDL.Text,
    'location' : IDL.Text,
  });
  const ShiftJobId = IDL.Nat;
  const ShiftJob = IDL.Record({
    'id' : ShiftJobId,
    'jobRole' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'company' : IDL.Text,
    'shiftStart' : IDL.Text,
    'shiftEnd' : IDL.Text,
    'shiftType' : IDL.Text,
    'location' : IDL.Text,
  });
  const InterviewId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Interview = IDL.Record({
    'id' : InterviewId,
    'jobRole' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'company' : IDL.Text,
    'location' : IDL.Text,
  });
  const ApplicationId = IDL.Nat;
  const Application = IDL.Record({
    'id' : ApplicationId,
    'appliedAt' : Timestamp,
    'interviewId' : IDL.Opt(InterviewId),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'skills' : IDL.Text,
    'qualification' : IDL.Text,
  });
  const ApplicationInput = IDL.Record({
    'interviewId' : IDL.Opt(InterviewId),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'skills' : IDL.Text,
    'qualification' : IDL.Text,
  });
  
  return IDL.Service({
    'addShiftJob' : IDL.Func([NewShiftJob], [ShiftJob], []),
    'getActiveInterviews' : IDL.Func([], [IDL.Vec(Interview)], ['query']),
    'getAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getInterview' : IDL.Func([InterviewId], [IDL.Opt(Interview)], ['query']),
    'getShiftJobs' : IDL.Func([], [IDL.Vec(ShiftJob)], ['query']),
    'submitApplication' : IDL.Func(
        [ApplicationInput],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };